services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/stock-rebalancer
      - /usr/src/stock-rebalancer/target
    container_name: stock-rebalancer
    ports:
      - "8080:8080"
