apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-rebalancer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-rebalancer
  template:
    metadata:
      labels:
        app: stock-rebalancer
    spec:
      containers:
      - name: stock-rebalancer
        image: stock-rebalancer-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /_healthy
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /_ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3